dist: trusty
# While 'sudo' is not used explicity, setting it to 'required' enforces full virtualization.
# This is needed as container-based images fail to build Seastar due to insufficient memory.
sudo: required
language: cpp
compiler: gcc
addons:
    apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libaio-dev
          - ninja-build
          - ragel
          - libhwloc-dev
          - libnuma-dev
          - libpciaccess-dev
          - libcrypto++-dev
          - libboost1.55-all-dev
          - libxml2-dev
          - xfslibs-dev
          - libgnutls28-dev
          - liblz4-dev
          - libsctp-dev
          - g++-5
          - make
          - libprotobuf-dev
          - protobuf-compiler
          - python3
          - libunwind8-dev
          - systemtap-sdt-dev
          - libtool
          - cmake

before_script:
  - ./configure.py --mode=release --enable-dpdk --compiler=g++-5

script:
  - ninja -j`nproc --all`
